services:
  client-react-vite:
    image: client-react-vite
    build:
      context: ./client-react/
      dockerfile: Dockerfile
    init: true
    volumes:
      - ./client-react/vite.config.js:/usr/src/app/vite.config.js
    networks:
      - frontend
    ports:
      - 5173:5173

  api-node:
    labels:
      shipyard.route: '/api/node/'
      shipyard.route.rewrite: true
    image: api-node
    build:
      context: ./api-node/
      dockerfile: Dockerfile
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000
    restart: unless-stopped

  api-golang:
    labels:
      shipyard.route: '/api/golang/'
      shipyard.route.rewrite: true
    image: api-golang
    build:
      context: ./api-golang/
      dockerfile: Dockerfile
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080
    restart: unless-stopped

  db:
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=foobarbaz
    networks:
      - backend
    ports:
      - 5432:5432

  init-db:
    image: postgres:15.1-alpine
    depends_on:
      - db
    volumes:
      - ./db/schema.sql:/scripts/schema.sql:ro
      - ./db/seed-data.sql:/scripts/seed-data.sql:ro
    environment:
      - PGPASSWORD=foobarbaz
    entrypoint: >
      /bin/sh -c "
      sleep 10 &&
      psql -h db -U postgres -f /scripts/schema.sql &&
      psql -h db -U postgres -f /scripts/seed-data.sql
      "
    networks:
      - backend

volumes:
  pgdata:

networks:
  frontend:
  backend:
